"""
paper writer unit and integration tests.

tests the full workflow: create → save → compile → download → delete.
also tests error cases like bad latex, missing projects, and ai generation.
"""

import os
import sys
import json
import time
import subprocess
import shutil

# add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from domain.paper_writer.compiler import (
    create_project,
    save_source,
    compile_pdf,
    get_source,
    list_projects,
    delete_project,
    _get_project_dir,
)

PASS = 0
FAIL = 0


def report(name, passed, detail=""):
    global PASS, FAIL
    if passed:
        PASS += 1
        print(f"  ✅ {name}")
    else:
        FAIL += 1
        print(f"  ❌ {name}: {detail}")


def test_create_project():
    """test that creating a project returns correct structure and writes files."""
    print("\n[1] create project")
    result = create_project("test paper alpha")
    report(
        "returns project_id",
        "project_id" in result and len(result["project_id"]) == 12,
    )
    report("returns name", result.get("name") == "test paper alpha")
    report("returns source", len(result.get("source", "")) > 0)

    # check files on disk
    project_dir = _get_project_dir(result["project_id"])
    report("main.tex exists", (project_dir / "main.tex").exists())
    report("meta.json exists", (project_dir / "meta.json").exists())

    meta = json.loads((project_dir / "meta.json").read_text())
    report("meta has correct name", meta.get("name") == "test paper alpha")

    return result["project_id"]


def test_get_source(project_id):
    """test reading source back from disk."""
    print("\n[2] get source")
    source = get_source(project_id)
    report("source is non-empty", len(source) > 0)
    report("source contains documentclass", r"\documentclass" in source)
    return source


def test_save_source(project_id):
    """test saving modified source."""
    print("\n[3] save source")
    custom_source = r"""\documentclass[12pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{hyperref}
\usepackage[margin=1in]{geometry}

\title{test paper from unit test}
\author{thinkstack test suite}
\date{\today}

\begin{document}
\maketitle

\section{introduction}
this is a test document generated by the thinkstack paper writer unit tests.

\section{methodology}
we test the full pipeline: create, save, compile, delete.

\section{results}
all tests should pass.

\end{document}
"""
    result = save_source(project_id, custom_source)
    report("save returns status", result.get("status") == "saved")

    # verify it was written
    read_back = get_source(project_id)
    report("saved content matches", read_back == custom_source)
    return custom_source


def test_compile_pdf(project_id):
    """test compiling latex to pdf."""
    print("\n[4] compile pdf")
    pdf_path, _warnings = compile_pdf(project_id)
    report("pdf path returned", pdf_path is not None)
    report("pdf file exists", pdf_path.exists())
    report("pdf file has content", pdf_path.stat().st_size > 0)

    # check it's actually a pdf (magic bytes)
    with open(pdf_path, "rb") as f:
        header = f.read(5)
    report("pdf has correct magic bytes", header == b"%PDF-")
    return pdf_path


def test_compile_bad_latex(project_id):
    """test that recoverable bad latex degrades gracefully (overleaf-style):
    a PDF is still produced and the error is surfaced as a warning, rather than
    the whole compile failing."""
    print("\n[5] compile bad latex (graceful recovery)")
    bad_source = r"""
\documentclass{article}
\begin{document}
Some valid text before the problem.
\undefinedcommandthatwillfail{this should error}
Some valid text after the problem.
\end{document}
"""
    save_source(project_id, bad_source)
    try:
        pdf_path, warnings = compile_pdf(project_id)
        report("bad latex still produces a pdf", pdf_path.exists())
        report("recovered errors surfaced as warnings", len(warnings) > 0)
    except RuntimeError as e:
        report("bad latex degrades gracefully", False, f"raised instead: {e}")


def test_list_projects(project_id):
    """test listing all projects."""
    print("\n[6] list projects")
    projects = list_projects()
    report("returns a list", isinstance(projects, list))
    report("list is non-empty", len(projects) > 0)

    found = any(p["project_id"] == project_id for p in projects)
    report("our project is in the list", found)

    # check has_pdf field
    our_proj = next((p for p in projects if p["project_id"] == project_id), None)
    report("project has has_pdf field", our_proj is not None and "has_pdf" in our_proj)


def test_save_source_missing_project():
    """test saving to a non-existent project."""
    print("\n[7] save to missing project (error handling)")
    try:
        save_source("nonexistent123", "some content")
        report("missing project raises error", False, "no error raised")
    except FileNotFoundError:
        report("missing project raises FileNotFoundError", True)


def test_get_source_missing_project():
    """test getting source from a non-existent project."""
    print("\n[8] get source from missing project (error handling)")
    try:
        get_source("nonexistent123")
        report("missing project raises error", False, "no error raised")
    except FileNotFoundError:
        report("missing project raises FileNotFoundError", True)


def test_delete_project(project_id):
    """test deleting a project."""
    print("\n[9] delete project")
    result = delete_project(project_id)
    report("delete returns True", result is True)

    # verify it's gone
    project_dir = _get_project_dir(project_id)
    report("project directory removed", not project_dir.exists())

    # double-delete should return False
    result2 = delete_project(project_id)
    report("double delete returns False", result2 is False)


def test_delete_missing_project():
    """test deleting a non-existent project."""
    print("\n[10] delete missing project")
    result = delete_project("nonexistent_id")
    report("returns False for missing project", result is False)


def test_api_endpoints():
    """test the full api workflow via http."""
    print("\n[11] api endpoint integration test")

    server = subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "main:app", "--port", "8111"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    time.sleep(6)

    try:
        import httpx

        base = "http://127.0.0.1:8111/api/papers"

        # create
        res = httpx.post(f"{base}/projects", json={"name": "api test paper"}, timeout=15.0)
        report("POST /projects returns 200", res.status_code == 200)
        data = res.json()
        pid = data["project_id"]
        report("response has project_id", len(pid) == 12)

        # list
        res = httpx.get(f"{base}/projects", timeout=10.0)
        report("GET /projects returns 200", res.status_code == 200)
        projects = res.json()["projects"]
        report("project appears in list", any(p["project_id"] == pid for p in projects))

        # get
        res = httpx.get(f"{base}/projects/{pid}", timeout=10.0)
        report("GET /projects/:id returns 200", res.status_code == 200)
        report("response has source", len(res.json()["source"]) > 0)

        # save
        latex_src = r"""\documentclass{article}
\begin{document}
hello from the api test.
\end{document}
"""
        res = httpx.post(
            f"{base}/save",
            json={"project_id": pid, "source": latex_src},
            timeout=10.0,
        )
        report("POST /save returns 200", res.status_code == 200)

        # compile
        res = httpx.post(f"{base}/compile", json={"project_id": pid}, timeout=30.0)
        report("POST /compile returns 200", res.status_code == 200)
        report("response has pdf_url", "pdf_url" in res.json())

        # download
        res = httpx.get(f"{base}/download/{pid}", timeout=10.0)
        report("GET /download/:id returns 200", res.status_code == 200)
        report("response is pdf", res.headers.get("content-type", "").startswith("application/pdf"))

        # delete
        res = httpx.delete(f"{base}/projects/{pid}", timeout=10.0)
        report("DELETE /projects/:id returns 200", res.status_code == 200)

        # verify gone
        res = httpx.get(f"{base}/projects/{pid}", timeout=10.0)
        report("deleted project returns 404", res.status_code == 404)

    except Exception as e:
        report("api test", False, str(e))
    finally:
        server.terminate()
        server.wait()


def main():
    print("=" * 50)
    print("thinkstack paper writer — test suite")
    print("=" * 50)

    # unit tests (no server needed)
    pid = test_create_project()
    test_get_source(pid)
    test_save_source(pid)
    test_compile_pdf(pid)
    test_compile_bad_latex(pid)
    test_list_projects(pid)
    test_save_source_missing_project()
    test_get_source_missing_project()
    test_delete_project(pid)
    test_delete_missing_project()

    # api integration test
    test_api_endpoints()

    # summary
    total = PASS + FAIL
    print(f"\n{'=' * 50}")
    print(f"results: {PASS}/{total} passed, {FAIL} failed")
    print(f"{'=' * 50}")

    sys.exit(1 if FAIL > 0 else 0)


if __name__ == "__main__":
    main()
